---
- name: ensure ownership
  file:
    path: "{{ django_base_dir }}/{{ django_project_name }}"
    state: directory
    recurse: yes
    owner: "{{ django_user_name }}"
    group: "www-data"

- name: ensure logs
  file:
    path: "{{ django_log_dir }}"
    state: directory
    recurse: yes
    owner: "{{ django_user_name }}"
    group: "www-data"
    mode: 2775

